# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Brian Mechanisms Robotics
email: media@cseco.co.ke
description: >- # this means to ignore newlines until "baseurl:"
  A robotics company in Kenya revolutionizing robotics for agricultural, manufacturing, construction and education; producing WaCaR walking robots.
shortDescription: >- # add \n at the end of each line
  Revolutionizing Robotics for\n Agriculture, Manufacturing, and Construction.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  pages:
    output: true
    # permalink: /:basename:output_ext
    permalink: /{{ page.name  }}



startYear: "2018"
owner: Brian Mechanisms Robotics

bannerLinks:
  robots: robots
  papers: papers
  simulator: simulator

navPages:
  robots: index.html#two
  papers: papers.html
  software: software.html
  about:
    about us: about.html
    team: team.html
  contacts: contact.html

logo: logo.png

## Start Contacts:
Contact:
  Telephone: "+254722329129"
  Email: media@cseco.co.ke
  Youtube: brianmechanisms
  Linkedin: "brian-mechanisms-robotics"
  Github: brianmechanisms
  Whatsapp: "+254706662011"
  LocationCoordinates: -0.537426,34.716525
  LocationName: Oyugis, Kobala
## EOContacts
SiteConfig:
    analytics: G-G3XQGQ1WY2
    formDev:  89da2faeb17558412bc697c03d17c48b
    formProd:  89da2faeb17558412bc697c03d17c48b
    domainDev: http://ubuntu.cseco.co.ke:4002
    domainProduction: https://www.cseco.co.ke
numParagraphsSummary: 2
# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
