name: Process Resumes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prep
        run: |
          cd scripts/resumes/ && ./cvProcessor.sh 

